GET http://localhost:8000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWxleCIsImlhdCI6MTYxOTY1NjQ0NCwiZXhwIjoxNjE5NjU2NDU5fQ.l9W-efFEVdbxXIpp9zcjHD431gMzZzPc6XzSGheKuFg

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWxleCIsImlhdCI6MTYxOTY1NjQyMH0.TVzAXrv2GJAeT16V3maJ9I0Na9P7Y014N9emEidsNe8"
}


###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Alex"
}

###