GET http://localhost:4000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWxleCIsImlhdCI6MTYxOTY1MzkyMX0.YrrJ7y82qTI-7leeqWUrlNU0bPZo8qKlYDg90sj_O4E

###

POST http://localhost:8000/login
Content-Type: application/json

{
    "username": "Alex"
}

###